MA/Paper: Display a warning when changing datum values
jacekkopecky/living-meta-analysis pull request #74
Opened 2017-04-27 12:50 UTC by Jnnybrrn

When the user focuses on a datum which is not empty, change
the class of the changewarning field to re-trigger the animation.

The warning will pulse once from black -> red -> black.

In addition, populate this warning box on page load ONLY if the
datum is not empty, to prevent any wierd popping from focus/unfocus.

2017-04-27 12:52 UTC, Jnnybrrn commented
Trello card - https://trello.com/b/WDTttp0z/lima

2017-05-09 12:32 UTC, jacekkopecky requested changes
small tweaks required

2017-05-09 12:32 UTC, jacekkopecky commented on webpages/js/metaanalyses.js
> +              _.fillEls(td, '.changewarning', "When updating an existing value, consider leaving a comment justifying the change.")
please move the content into the HTML

2017-05-09 12:32 UTC, jacekkopecky commented on webpages/js/metaanalyses.js
> +            // Set up a listener to onfocus trigger the animation on the warning element
this may be replaced in CSS by
```
.value.editing:focus + .datum.popupbox .changewarning { animation: ... }
```
not sure about `:focus`

2017-05-09 12:32 UTC, jacekkopecky commented on webpages/profile/metaanalysis.html
> +
fixme

2017-05-10 09:30 UTC, Jnnybrrn commented
New commit w/ feedback changes, ready for review

2017-05-10 15:54 UTC, merged