Minor html changes colours
jacekkopecky/living-meta-analysis pull request #78
Opened 2017-05-02 13:03 UTC by Beyond-Birthday

Changed colours according to the meeting on 01/05

- Changed dark blue to softer version
- Added soft litlle gradient like in apple's website

2017-05-09 12:53 UTC, jacekkopecky requested changes
mainly two things: there seems to be some code from a different PR here; and we have some colour suggestions around the gradients because we haven't talked about these gradients before.

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/css/main.css
> +  /*background-color: #c4ebf1; /* from poster */
please remove this, no need to keep old values here and in places like this.

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/css/main.css
> +main.index > section.columns > section > h2.second_title {
this block of code is from a different PR, isn't it? If it is, please remove it from here.

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/css/main.css
> +  background-image: linear-gradient(to bottom, #D6EDFE, #DADAFE);
not sure we like the red hue; how would you feel about this: have here what you have on line 228; and then change line 228 to go `to top` so the light bit is by the dark section.

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/css/main.css
> +  background-image: linear-gradient(to bottom, #0484E6, #3992D6);
together with the suggestion above, this could be a solid color, what do you think?

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/css/main.css
> +main.index > section > ul {
the lines above from 270 seem to come from a different PR, is that correct? If so, please remove them here.

2017-05-09 12:53 UTC, jacekkopecky commented on webpages/index.html
> +      <h2 class = "second_title">First actions:</h2>
this PR probably shouldn't be changing index.html, only the colors in the CSS

2017-05-09 13:05 UTC, Beyond-Birthday commented on webpages/css/main.css
> +  background-image: linear-gradient(to bottom, #0484E6, #3992D6);
In meeting with Tomas, we discuss about Apple's website, where there is such gradients. So I was testing if these looks good or not and discuss these changes w/ the rest of the team, this is why also there is comment with previous versions.

2017-05-09 13:06 UTC, Beyond-Birthday commented on webpages/css/main.css
> +main.index > section > ul {
Totally ! My bad ! Will remove them soon !

2017-05-10 15:45 UTC, jacekkopecky commented
Thanks @Beyond-Birthday !
Merged in b3436d341a968a6148956ba44f1ad0449e743cf4

2017-05-10 15:45 UTC, closed without merging