Commit for graph colours
jacekkopecky/living-meta-analysis pull request #79
Opened 2017-05-02 13:37 UTC by Beyond-Birthday

Changes the colours of the graph both in homepage (index.html) and in meta-analysis page.

2017-05-09 13:03 UTC, jacekkopecky requested changes
thanks, the requested changes are mostly just code style comments

2017-05-09 13:03 UTC, jacekkopecky commented on webpages/js/metaanalyses.js
> +      currentGroup = currentGroup + 1;
please use `+= 1` here, it's more readable

also, please consider starting from 0 on line 950 and putting this increment after the value is used on line 998

2017-05-09 13:03 UTC, jacekkopecky commented on webpages/js/metaanalyses.js
> +        grapeEl.classList.add('c' + currentGroup%7);
the number 7 needs to come from a dataset value please, so we have the number of groups and their styles in one place in the SVG template

2017-05-09 13:03 UTC, jacekkopecky commented on webpages/profile/metaanalysis.html
> +
too many empty lines, one will do

2017-05-09 13:03 UTC, jacekkopecky commented on webpages/index.html
> +        .grape.c0 {
please fix the indentation of the following few lines

2017-05-09 13:07 UTC, Beyond-Birthday commented on webpages/js/metaanalyses.js
> +      currentGroup = currentGroup + 1;
Yep, the '-1' thing is just an old habit !

2017-05-09 16:49 UTC, Raphael-R-R commented on webpages/index.html
> +        .grape.c0 {
Done

2017-05-09 16:50 UTC, Raphael-R-R commented on webpages/profile/metaanalysis.html
> +
Done

2017-05-09 17:01 UTC, Raphael-R-R commented on webpages/js/metaanalyses.js
> +        grapeEl.classList.add('c' + currentGroup%7);
Done

2017-05-09 17:03 UTC, Raphael-R-R commented on webpages/js/metaanalyses.js
> +      currentGroup = currentGroup + 1;
Done

2017-05-10 15:34 UTC, jacekkopecky commented
Thanks!

Merged in e7a678e00373bde32e2d636e11a6a9a880ead980

2017-05-10 15:34 UTC, closed without merging